### ISSUE TITLE
Error: unknown exception Command exited with non-zero status 1

### ISSUE THREAD

**Issue by cecile-meier-scherling** [refresh-bio/SPLASH#6]
Hello, I have tried running splash with a couple of different fastq datasets, but I am running into the following error:
```
Error: unknown exception
Command exited with non-zero status 1
```
I have formatted the input file as described, where each sample is per line, and each line contains the sample name and the path to the sample separated by a space. The path to the input sample files is with respect to the working directory. Currently, my input file contains 16 fastq files.

I have tried to debug this error by running splash on different fastq files. However, I am getting the same error which makes me think there may be an issue with the formatting of my input file. 

Does anyone else have experienced this error while running splash?

**Comment by marekkokot** [comment]
Hello, thank you for reporting. According to your description, I think you are doing everything right.
Could you please try to prepare some fake fastq files (just with a couple of arbitrary reads) and check if it also fails and if so, share these files, your input, and the exact command line you are using?

You may also try using the content of the `example` directory. There is `download.py` script to download exemplary input data and the `input.txt` and you may run splash on this and let me know if this also fails.

BTW. I think this error cames from KMC which is a part of SPLASH pipeline, and it occurs in most cases when there is something wrong with the input. For example if one uses fasta instead of fastq files this may occur, but as I understand you are using fastq files.

Anyway thank you for reporting and let me know if more info is needed at this point and how the above went.

**Comment by cecile-meier-scherling** [comment]
Thank you, @marekkokot for your response! I should have mentioned that the example data works fine, and I don't run into any issues. I will make some fake fastq files and run splash and will keep you updated.

**Comment by marekkokot** [comment]
Ok, if it works on fake files, maybe you could take a `head` of your real files and check them. BTW. how big are your input files? Maybe there is a way to share them?

**Comment by cecile-meier-scherling** [comment]
Hello, I created some fake fastq files using the fastq_generator ([https://github.com/johanzi/fastq_generator]) and ran SPLASH, which gave me the same error as before. I have attached my input file and fake fastq files. 

[fake_fastq_input.txt](https://github.com/refresh-bio/SPLASH/files/12043916/fake_fastq_input.txt)
[test3.fastq.gz](https://github.com/refresh-bio/SPLASH/files/12043917/test3.fastq.gz)
[test2.fastq.gz](https://github.com/refresh-bio/SPLASH/files/12043919/test2.fastq.gz)
[test1.fastq.gz](https://github.com/refresh-bio/SPLASH/files/12043920/test1.fastq.gz)

**Comment by marekkokot** [comment]
Hi, thanks. I downloaded but it seems these files are not gzipped, although they have *.gz in name. In such case SPLASH will try to gunzip them. Maybe this is the reason. If your files are in fact plain text and not *.gz try to rename it to just be *.fastq.
Let me know if this helps.

**Comment by cecile-meier-scherling** [comment]
Thank you very much - that solved the issue!
